### ISSUE TITLE
Can u add count function for those capsules ?

### ISSUE THREAD

**Issue by Yuyuko-sama** [jojobii-arks/ngs-log-observer#14]
Need to know how many capsules u get instead of finding out what u get after kill those monsters.

**Comment by Yuyuko-sama** [comment]
also maybe we can add count for killing monsters?(u can get mst from each monsters,use this to detect) owo

**Comment by jojobii-arks** [comment]
> also maybe we can add count for killing monsters?(u can get mst from each monsters,use this to detect) owo

I was considering this, but I was worried that the Meseta rewards from trials and possibly autosell may end up getting in the way of this...

I might be able to find a way to filter the ones that "are most likely enemy kills" tho!

**Comment by Yuyuko-sama** [comment]
hum，trials reward only have 1000 1500 choice.
autosell msg and mst drop msg from enemy kills are different tho.

**Comment by Yuyuko-sama** [comment]
Check if Action is a pickup of Meseta (Enemy Kill)
https://github.com/PureFallen/NGSPSECount/blob/d1b797e3cb5070d0d9930a9c6cf152c974b96af6/NGSPSECount.py#L129
 Check if pick of Meseta is caused by a trial clear
https://github.com/PureFallen/NGSPSECount/blob/d1b797e3cb5070d0d9930a9c6cf152c974b96af6/NGSPSECount.py#L131

but yea it's difficult to distinguish between autosell and enemy kill,msg in logs seems no difference.

**Comment by Yuyuko-sama** [comment]
maybe we can add count function for capsules（also fot those tickets） first? owo

**Comment by Yuyuko-sama** [comment]
hum if we can make sure that autosell msg is a separate one not include in enemy drop mst,maybe there is a way fot this.
like autosell only work for equipments ,we can log those items' prices and make a list .
